"""add FK activity_logs.telegram_id -> users.telegram_id

Revision ID: 3f63173a9ac3
Revises: 78c75147fa14
Create Date: 2025-08-08 12:41:49.627678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f63173a9ac3'
down_revision: Union[str, Sequence[str], None] = '78c75147fa14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
