"""remove unique on username

Revision ID: 78c75147fa14
Revises: 96e2802635c9
Create Date: 2025-08-08 11:20:06.965040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c75147fa14'
down_revision: Union[str, Sequence[str], None] = '96e2802635c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_logs_telegram_id_fkey'), 'activity_logs', type_='foreignkey')
    op.drop_index(op.f('ix_users_username_lower'), table_name='users')
    op.create_index('ix_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username_lower', table_name='users')
    op.create_index(op.f('ix_users_username_lower'), 'users', [sa.literal_column('lower(username::text)')], unique=True)
    op.create_foreign_key(op.f('activity_logs_telegram_id_fkey'), 'activity_logs', 'users', ['telegram_id'], ['telegram_id'])
    # ### end Alembic commands ###
