"""Initial Migration

Revision ID: 96e2802635c9
Revises: 
Create Date: 2025-08-07 16:41:04.001727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e2802635c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram user ID who performed the action'),
    sa.Column('action_type', sa.Enum('REGISTER', 'SEND_MESSAGE', 'READ_MESSAGE', 'SHARE_MESSAGE', 'DELETE_ACCOUNT', 'LOGIN', 'LOGOUT', name='actiontype'), nullable=False, comment='Type of action performed'),
    sa.Column('details', sa.JSON(), nullable=True, comment='Additional details about the action in JSON format'),
    sa.Column('ip_info', sa.String(length=100), nullable=True, comment='IP address and other connection info'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='User agent string from the request'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the activity was logged'),
    sa.PrimaryKeyConstraint('id'),
    comment='Audit log of user activities and actions'
    )
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_telegram_id'), 'activity_logs', ['telegram_id'], unique=False)
    op.create_index('ix_activity_logs_telegram_id_created_at', 'activity_logs', ['telegram_id', 'created_at'], unique=False)
    op.create_table('global_stats',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('stat_date', sa.DateTime(), nullable=False, comment='The date these statistics are for (typically start of day)'),
    sa.Column('total_users', sa.Integer(), nullable=False, comment='Total number of registered users'),
    sa.Column('active_users', sa.Integer(), nullable=False, comment='Number of active users in the last 30 days'),
    sa.Column('messages_sent_today', sa.Integer(), nullable=False, comment='Number of messages sent on this day'),
    sa.Column('new_registrations', sa.Integer(), nullable=False, comment='Number of new user registrations on this day'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When this stats record was created'),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores daily aggregated statistics about the application'
    )
    op.create_index(op.f('ix_global_stats_stat_date'), 'global_stats', ['stat_date'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram user ID (from Telegram API)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='User-chosen display name'),
    sa.Column('telegram_username', sa.String(length=50), nullable=True, comment='Telegram username (with @), if available'),
    sa.Column('unique_code', sa.String(length=30), nullable=False, comment='Unique code for sharing messages with this user'),
    sa.Column('total_messages_received', sa.Integer(), nullable=False, comment='Total number of messages received by this user'),
    sa.Column('total_messages_sent', sa.Integer(), nullable=False, comment='Total number of messages sent by this user'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user account is active'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the user account was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When the user record was last updated'),
    sa.Column('last_activity', sa.DateTime(), nullable=False, comment='Timestamp of last user activity'),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores user account information'
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_telegram_username'), 'users', ['telegram_username'], unique=False)
    op.create_index(op.f('ix_users_unique_code'), 'users', ['unique_code'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index('ix_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('anonymous_messages',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='Public unique identifier for sharing'),
    sa.Column('recipient_id', sa.Integer(), nullable=False, comment='Recipient user ID'),
    sa.Column('sender_telegram_id', sa.BigInteger(), nullable=False, comment='Sender Telegram ID (remains anonymous to recipient)'),
    sa.Column('message_content', sa.Text(), nullable=False, comment='The actual message content (encrypted in transit)'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Whether the message has been read by the recipient'),
    sa.Column('shared_count', sa.Integer(), nullable=False, comment='Number of times this message has been shared'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the message was created'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='When the message was first read (if read)'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    comment='Stores anonymous messages between users'
    )
    op.create_index(op.f('ix_anonymous_messages_created_at'), 'anonymous_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_anonymous_messages_recipient_id'), 'anonymous_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_anonymous_messages_sender_telegram_id'), 'anonymous_messages', ['sender_telegram_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram user ID this session belongs to'),
    sa.Column('session_type', sa.Enum('SETUP', 'SENDING_MESSAGE', 'BROWSING_INBOX', name='sessiontype'), nullable=False, comment='Type of session (e.g., setup, sending_message, etc.)'),
    sa.Column('target_user_id', sa.Integer(), nullable=True, comment='Target user ID for this session (if applicable)'),
    sa.Column('current_step', sa.String(length=50), nullable=True, comment='Current step in the session flow'),
    sa.Column('session_data', sa.JSON(), nullable=True, comment='JSON-encoded session data (state)'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='When this session expires'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the session was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When the session was last updated'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores user session data for multi-step interactions'
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_target_user_id'), 'user_sessions', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_telegram_id'), 'user_sessions', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_telegram_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_target_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_anonymous_messages_sender_telegram_id'), table_name='anonymous_messages')
    op.drop_index(op.f('ix_anonymous_messages_recipient_id'), table_name='anonymous_messages')
    op.drop_index(op.f('ix_anonymous_messages_created_at'), table_name='anonymous_messages')
    op.drop_table('anonymous_messages')
    op.drop_index('ix_users_username_lower', table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_unique_code'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_global_stats_stat_date'), table_name='global_stats')
    op.drop_table('global_stats')
    op.drop_index('ix_activity_logs_telegram_id_created_at', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_telegram_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
